[tool.pytest.ini_options]
addopts = "--maxfail=1 --disable-warnings -q --cov=tp_jour_3 --cov-report=term-missing --no-cov-on-fail"
testpaths = [
    "tests"
]

python_files = [
    "test_*.py"
]

[tool.coverage.run]
branch = true
source = ["tp_jour_3"]

[tool.coverage.report]
exclude_lines = [
    "pragma: no cover",
    "if __name__ == .__main__.:",
]
